### ISSUE TITLE
T5.5 Token Shaman/Hunter/Warrior problems

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#100]
## Expected Behavior
That at least one token will be from the boss after the full passage of the raid.

## Current Behavior
3 races were done - just one token, and also no tokens from premium bags. 
I tried it on the shaman today, on the warrior yesterday and on the hunter about a week ago. The picture is the same. Not that I'm a loser of some kind, they really don't dropped.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenukshwow** [comment]
The token does drop.
