### ISSUE TITLE
Starter Weapon and Shield not being recognized as melee weapon & shield

### ISSUE THREAD

**Issue by samullai2** [HeroesWoW/BugReports#101]
I just created a paladin and I have starter gear, and I can't use skills that require Melee Weapon or Shields, like Crusader Strike, Divine Storm, Holy Shield. It's been a sad experience to level up and solo T1 without those abilities.

**Comment by Fenukshwow** [comment]
Download the latest enchant patch from the website and extract it into your data folder. Restart your game and your issue is resolved.

**Comment by samullai2** [comment]
thanks!
