### ISSUE TITLE
Wrong Stats on Xbows

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#102]
## Current Behavior
Wrong dmg on weapon

##  Screenshots

![-1](https://user-images.githubusercontent.com/35656427/50077770-fde48680-01ed-11e9-9a02-98a2761cb8ba.png)

**Comment by Fenukshwow** [comment]
I don't see any issue, could you explain your issue a bit more?

**Comment by fpalfapvp** [comment]
Wrong screen -_-

Look at Damage. 
t5.5 38850-47250
t6    38850-47250
t7    42216-51345
![sd](https://user-images.githubusercontent.com/35656427/50174100-f7dfca00-0301-11e9-8752-178f4cdb3c1e.png)


Same with hunter items, lots of t5.5 and t6 items have lower stats than t4.

**Comment by Fenukshwow** [comment]
Crossbow dmg and item level is fixed.
