### ISSUE TITLE
[Unlimited] Hunter T5.5 Stats problems.

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#103]
## Expected Behavior
When im start change my T2 to T5 i think its give me good boost for stats. But... 

## Current Behavior
1. All T1 and T2 items have more stamina then t3/t4/5 (make screen for example)
2. T6/T7/T8 Backs have lower ARP than T5.5/T5/T4/T3/T2/T1

## Possible Solution
1. Change values to correct.

##  Screenshots

![default](https://user-images.githubusercontent.com/35656427/50222429-e1d51680-03a0-11e9-84a0-7cba18b0bacc.png)
![3](https://user-images.githubusercontent.com/35656427/50222843-27deaa00-03a2-11e9-9f3d-8297dea2412a.png)

**Comment by Fenukshwow** [comment]
Fixed
