### ISSUE TITLE
[Unlimited] No items models on sets.

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#104]
## Current Behavior
1. T7 Hunter helm haven't model. 
2. T5 / T5.5 / T6 shoulders have problems with display
##  Screenshots
![d](https://user-images.githubusercontent.com/35656427/50223192-2497ee00-03a3-11e9-9b74-60642ebd4432.png)
![3d](https://user-images.githubusercontent.com/35656427/50223280-704a9780-03a3-11e9-9896-f6968e54d472.png)

**Comment by Fenukshwow** [comment]
Fixed T7 head moddel however the T6 shoulders are displayed fine to me.
