### ISSUE TITLE
[Unlimited] Black Market Donation - items problems

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#105]
## Current Behavior
1. Twice duplicated Haste Donor Shirt III and Haste Donor Tabard III ;
2. Haven't Donor Tabard IV;
3. Have't next levels of Donors Backpack;

## Possible Solution
1. Delete duplicated items;
2. Add Donor Tabard IV;
3. Add next levels of Donors Backpack;

##  Screenshots
https://youtu.be/HEA09F8cUpw

**Comment by Demifer** [comment]
1.  The "duplicated" items are with only GC cost. They were made for a direct purchase if a player wants to get instantly one, without upgrading step by step.
2. Donor Tabard IV is on the 1st page of Black Market Donations tab.
3. About donor backpacks - they are not meant with more levels, at least yet. It's a matter of suggestions, not a bug.
