### ISSUE TITLE
bugged mail

### ISSUE THREAD

**Issue by dani531h** [HeroesWoW/BugReports#106]
i was going in tier 5.5 raid and i had pvp armor on and i forgot to change when i was back after the raid i go to my mail to get the pvp armor when i open the mail i see no pvp armor and i dont know what to do now
## Expected Behavior
you maybe can help me get it back because i used alot of time to get it

## Current Behavior
i dont know i dont get it i guess

## Possible Solution
i think you should look and see if it is bugged cuz i need my stuff

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
getting it back and losing it

**Comment by Fenukshwow** [comment]
When you relog it is fixed.

**Comment by dani531h** [comment]
ok thank you very much

Den man. 7. jan. 2019 kl. 20.35 skrev Fenuks <notifications@github.com>:
