### ISSUE TITLE
[Unlimited] A2 Wands give lowest relilience than A1

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#107]
## Current Behavior
All A2 Wands have 216 res but A1 wand have 229

## Possible Solution
Make more relilience on A2 wands or nerf A1 wands.

##  Screenshots
![d](https://user-images.githubusercontent.com/35656427/50981011-a8587c80-1502-11e9-8b9e-e49f840458d6.png)

**Comment by Fenukshwow** [comment]
Fixed
