### ISSUE TITLE
bug when enter chara to games / specially to map t4 and use windows 7 pc

### ISSUE THREAD

**Issue by ahmad2ss** [HeroesWoW/BugReports#110]
https://ibb.co/mHjvz7T
![Untitled](https://user-images.githubusercontent.com/48942835/54979926-e0c60d80-4fbd-11e9-8826-3ffffd97018b.png)
i got this proplem when i equip  [Mystical Skyfire Diamond] 
i dont know maybe its another proplem but what i think because i got to all teir but when i equip this in my head item  i got this proplem 
so what now can log in my chara this its my main chara
i try in the same account to enter in another chara i can but when i try in this what i told befor i got this message please help me
my name this chara tatorhealer
i am in zone t4
i enter the games in another pc another windows like widows 8 its work and chara work so?
so its porplem from windows 7 or what?
i try at the moment when i teleport to t4 in any character i got this message ? 
i download the games again fro hard disk to my pc have a windows and i go again this message 
so i think the problem is i think when i go t4 some files does not found something about load 
but now i didnt fix it so i will keep to play in another pc have windows 8 so i wiat to et have fix proplem 

i am wiating

**Comment by fpalfapvp** [comment]
Better re-download clietn from server. 
http://heroes-wow.com/HeroesWoWClient3.0.zip.torrent

**Comment by Fenukshwow** [comment]
Make sure you are up2date with the latest patch-9.mpq
