### ISSUE TITLE
RDF - Stuck on missing 1 DPS

### ISSUE THREAD

**Issue by Maltahl** [HeroesWoW/BugReports#113]
When queueing you are getting your "group" filled with all roles except for 1 DPS which will always be missing regardless off how many how queues DPS.

## Expected Behavior
RDF should fill out groups over time.

## Current Behavior
Stuck with 4/5 group with 1 DPS missing even if 3 dps queues with no alternative role.

## Possible Solution
Properly a regression after 2 April and properly server side.

## Steps to Reproduce
Either queue solo or as 3 DPS in RDF. Within a few seconds group is almost filled (except for the last dps slot) and is stuck like this even after multiple trys, relogs and waiting over 1 hour.

**Comment by fpalfapvp** [comment]
Its not even with dps. Same with one tank or one healer.
