### ISSUE TITLE
Druid Bash Not working

### ISSUE THREAD

**Issue by TheBestDruidTank** [HeroesWoW/BugReports#116]
## Expected Behavior
Bash is a Spell Usable in Bear or Dire Bear form For druids, an interrupting ability

## Current Behavior
 Bash Does not seem to connect, unable to interrupt any spell

## Steps to Reproduce

1.Attempt to Interrupt spells as druid using Bash Skill
2.
3.
4.

**Comment by fpalfapvp** [comment]
Its interrupt non-player spells or interruptable spells from mobs.

**Comment by Fenukshwow** [comment]
Daygu is right, closing it.
