### ISSUE TITLE
[Unlimited] T5 Caster Weapon Different ilvls

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#120]
## Expected Behavior
Spellblade of the Demon Blood - have 310 ilvl when it must have 320 ilvl.

## Current Behavior
Spellblade of the Demon Blood 

![31](https://user-images.githubusercontent.com/35656427/58235666-f2bbf680-7d49-11e9-9e61-a52524e7e0da.png)

**Comment by Fenukshwow** [comment]
Fixed
