### ISSUE TITLE
[Unlimited] To low stats on Hunter necks starting from T6

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#122]
## Expected Behavior
Have two problems.

## Current Behavior
1. Too low scale between shooting ranges from T5.5 and T6. And further, starting from T6, the picture is preserved.
2. T1 / T2 / T3 / T4 necks have more ARP then T5.5

##  Screenshots
![Безымя1нный](https://user-images.githubusercontent.com/35656427/58311605-06329480-7e12-11e9-9dca-e33d6bfc9d62.png)

**Comment by Fenukshwow** [comment]
It's low due to it being a middle tier. We won't increase the stats for now - this might come with the PvE balance.
