### ISSUE TITLE
Transmog NPC issues that haven't been dealt with (To my knowledge)

### ISSUE THREAD

**Issue by lordvolom1** [HeroesWoW/BugReports#128]
Donor transmog's and lots of others still not showing up in the mog npc when in your bank/inventory: item id's

Mogs from Fabio(Donor mog vendor) that im aware of (this should've been fixed by now):
-8800012
-8800013
-698201
-100800
-100801
-100802
-1250304

Random list of sets/mogs that don't show up:

-110515
-110513
-110511
-110510
-110512
-110516
-110516
-110514
-698225
-698224
-698227
-698226
-698221
-698228
-698222
-698223
-345002
-60601
-60541
-60516
-60604
-60605
-60603
-60602
-60605
-60423
-60426
-60424
-60427
-60564
-60557
-60425
-60559

idk if this helps at all but figured i'd post it.

**Comment by Fenukshwow** [comment]
https://github.com/HeroesWoW/BugReports/issues/124
