### ISSUE TITLE
[Urgent Bug] Unable to change race using Faction Change 

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#13]
## Description
When players try to change their faction, it says that they are part of team(or that they are are the team leader) and even when they aren't part of any team the error still appears
## Proof
https://www.youtube.com/watch?v=1AxlM_TLiYY
## Solution
Remove the unnecessary check for team and team leader, because the server is FFA and it is simple not needed

**Comment by nightbaneftw** [comment]
Updated the report, hope it gets fixed soon!

**Comment by Swiftsmoke** [comment]
Issue will be resolved with a core update.

_For Core Reference: 
e9167d1f86a30b346631dcd570ecfa93e7075b8f
b201855c8adf26c852a1348f5202d10184496635_
