### ISSUE TITLE
[Unlimited] Dire Maul (T7) Boss Encounter Doors

### ISSUE THREAD

**Issue by Brockers1** [HeroesWoW/BugReports#137]
## Expected Behavior
After a full wipe the doors that close after a boss encounter starts should open upon combat ending.

## Current Behavior

A full wipe happens, the boss successfully resets, loses all [Growth] buffs however the doors remain shut.

Wiping on the Second Boss keeps the green sludge at entrance closed
Wiping on Cturath has kept the large double doors after the second boss closed
## Possible Solution
Removing the encounter doors and prevent access to the instance during the encounter, but I'm a simpleton with no actual knowledge of the difficulty of step 2 :) 

## Steps to Reproduce

1.Start the boss encounter
2.fully wipe
3.no combat res
4.

## Detailed Description

The boss encounter doors for T7 are failing to open after a full party wipe this prevented us from returning to a second attempt to finish the T7 dungeon. You could possibly remove the doors and prevent access to the dungeon while an encounter is in progress instead.

## Possible Implementation

Remove the encounter doors as a quick fix but I'm no carpenter
##  Screenshots

![WoWScrnShot_112319_132657](https://user-images.githubusercontent.com/51338997/69479525-198cdf80-0df6-11ea-890b-7be9c4249c72.jpg)

**Comment by Fenukshwow** [comment]
Fixed
