### ISSUE TITLE
Damage increase buffs are stacking 

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#14]
http://us.battle.net/wow/en/game/patch-notes/3-1-0

> Hysteria, Tricks of the Trade, Enrage, Wrecking Crew, Death Wish, Arcane Power, Owlkin Frenzy, Beast Within, and Avenging Wrath damage bonuses no longer stack together.

All of them stack together in our server, will be great if you fix it

**Comment by Swiftsmoke** [comment]
The following spells are now in an exclusive group, meaning only 1 can be active at a time
[Hysteria](https://wotlk.evowow.com/?spell=49016)
[Arcane Power](https://wotlk.evowow.com/?spell=12042)
[Avenging Wrath](https://wotlk.evowow.com/?spell=31884)
[Death Wish](https://wotlk.evowow.com/?spell=12292)
[The Beast Within](https://wotlk.evowow.com/?spell=34471)
[Tricks of the Trade](https://wotlk.evowow.com/?spell=57933)

This will take effect next server restart

**Comment by nightbaneftw** [comment]
Warriors still can have 3 enrages on their self + Death Wish

https://wotlk.evowow.com/?spell=56614
https://wotlk.evowow.com/?spell=13048
https://wotlk.evowow.com/?spell=29594

The chance of having 3 of them to proc at the same time is low, but if this happens, warriors start oneshoting people. After all they get 60% damage increase:
100(10%) = 110(10%) = 121(10%) =133(20%) = 160 ... the difference between 100 and 160 is 60%
