### ISSUE TITLE
Mall guardians show PVP vendor waypoint as inside castle not in the crypt 

### ISSUE THREAD

**Issue by bwal123** [HeroesWoW/BugReports#145]
Mall guardian when selected to show pvp vendor location shows it in the first floor of the right side of castle, no vendor in that room. 

## Expected Behavior

Should set the waypoint to the crypt outside of mall where the PVP vendors actually are.
## Steps to Reproduce

1.go to mall guardian
2.select pvp vendor
3.
4.

**Comment by Fenukshwow** [comment]
Fixed
