### ISSUE TITLE
Black temple scaling changed after new patch 

### ISSUE THREAD

**Issue by Rasmusani** [HeroesWoW/BugReports#146]
## Expected Behavior

Melee to be above 1 mil dps
## Current Behavior

So i was doing bt with my almost full 10.5 shaman with donor weps trinket and sigil i was bearly doing 1 mil dps on any boss we had full donor paladin doing 800k dps all of a sudden

## Steps to Reproduce

1. 
2.
3.
4.

## Context (Environment)

So the scaling in bt changed after the new patch basically pala and shaman dps went from like top dps to bottom dps 
## Detailed Description

Im not sure maybe see if the scaling is wrong 
##  Screenshots

https://gyazo.com/e76e3caccee1dc21b7f993f055d0c6a5 
A screenshot of dps from gurtogg bloodboil

**Comment by Fenukshwow** [comment]
Fixed
