### ISSUE TITLE
Bt bosses dead before u get to them 

### ISSUE THREAD

**Issue by Rasmusani** [HeroesWoW/BugReports#147]
## Expected Behavior

The bosses aren´t suppoes to be dead even before we get to them
## Current Behavior

We tried resetting bt multiple times and the first boss is dead before we get there it was the same issue 2 days go 
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

It´s affecting me in a way where i can´t gear my chars to 10.5 cuz the bosses aren´t alive 

##  Screenshots

https://gyazo.com/6212a5850815661b6b277fa2f31deeb6

**Comment by Fenukshwow** [comment]
Fixed
