### ISSUE TITLE
we can't learn a recipe (cooking)

### ISSUE THREAD

**Issue by Albator66** [HeroesWoW/BugReports#148]
## Steps to Reproduce

1.buy the recipe on the screenshot
2.and use
3.you can see you eat the recipe x)
4.

## Context (Environment)

i learn all recipe and i see that it's so lol but i come for report that too

##  Screenshots

https://www.noelshack.com/2019-52-2-1577173989-screenshot-33.png
https://www.noelshack.com/2019-52-2-1577173991-screenshot-34.jpg

**Comment by Pangoken** [comment]
This recipe was like that from blizzard, not a bug, and this item was not aviable to players...
