### ISSUE TITLE
Quest don't trigger

### ISSUE THREAD

**Issue by Pangoken** [HeroesWoW/BugReports#149]
A Quest "Ending Their World" at least in the Fallen Heroes realm when accepted does not trigger.
## OpenWoW/WoWHead Link
https://www.wowhead.com/quest=9759/ending-their-world

## Expected Behavior
Legoso must go and plant all over Vector Coil and when reaching Sironas, Sironas becomes vulnerable.

## Current Behavior
Legoso not moving an inch.

## Possible Solution
At least make Sironas permenantly vulnerable.

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
I am doing a quest chain for a tabard and an achievement for a title.

**Comment by Fenukshwow** [comment]
We won't fix these quests as they are not part of our custom content.
