### ISSUE TITLE
Donor Backpacks spell penetration

### ISSUE THREAD

**Issue by Saphiron98** [HeroesWoW/BugReports#150]
## Expected Behavior
I got my 35 Spell pen by my cloak, but the donor backpacks doesnt give me the 30 spell pen at the charakter board, so, i dont know if i got that extra 30 spell pen, or is it just not shown?

## Possible Solution
Add the right Spell pen.

## Detailed Description
Not adding the spell pen as it got used to.

##  Screenshots
https://puu.sh/EYLJP/0a43abd7e1.png
https://puu.sh/EYLJM/d338007168.jpg
https://puu.sh/EYLJV/d2184c17c5.png

**Comment by Fenukshwow** [comment]
Fixed by Hawjiki.
