### ISSUE TITLE
Mounts

### ISSUE THREAD

**Issue by Saphiron98** [HeroesWoW/BugReports#151]
## Expected Behavior
I cant mount it,  "You can't use that here"

## Steps to Reproduce
Re-add it maybe

## Detailed Description
I can not use that 2 mounts i've been looking for. 

##  Screenshots
https://puu.sh/EZ0HP/888770c946.png
https://puu.sh/EZ0HT/e2f46c162e.png

**Comment by Fenukshwow** [comment]
Where are you trying to mount?

**Comment by Saphiron98** [comment]
Typical in Mall

**Comment by Fenukshwow** [comment]
Fixed
