### ISSUE TITLE
Account Management not possible

### ISSUE THREAD

**Issue by wxlam101010** [HeroesWoW/BugReports#153]
## Provide a general summary
FAQ forum form is 404, Change email form is 404, no contact form exist. No contact with the staff is possible.

## Expected Behavior
I should at least communicate with admin to request my recent account to be deleted.

## Current Behavior
FAQ forum form is 404 page, Change email form send 404 response too, no contact can exist de facto with the staff

## Possible Solution
Delete old account with less than 4 hours playing if not in use every "insert time period" ?

## Steps to Reproduce
1. Suscribe new account
2. Making a few test, founding that the server you have interested in is shutdown (it's life, it can happens, no problem here).
3. Wanting to delete the account.
4. Realizing there is no way to contact people on the website..

## Context (Environment)
Recent install (one hour has been play maximum)

## other
yooop@lavache.com to contact my friend account, me, i'm here on github =)

**Comment by Fenukshwow** [comment]
You can contact staff at discord or via forum: https://forum.heroes-wow.com/forums/115-Private-messages-to-Server-Staff

**Comment by wxlam101010** [comment]
Hi.

Thanks for the link =D.

But the current behavior section of my post is still relevant. The website is broken.

Good luck you all =)
