### ISSUE TITLE
Vote Issue Bugg

### ISSUE THREAD

**Issue by julsde12** [HeroesWoW/BugReports#166]
## Expected Behavior

cant even vote and get rewards
## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

Each time i log in to web page to vote i always get 24hours reset w/o voting....

##  Screenshots
https://www.facebook.com/messenger_photo/?fbid=163929635056464&message_id=mid.%24cAADoZFkgX694KIFHVVx9zv6uQJ4D

**Comment by Fenukshwow** [comment]
Make a forum post at our forum in the section private messages to server staff.
