### ISSUE TITLE
HOW TO FIX THIS

### ISSUE THREAD

**Issue by Bougah** [HeroesWoW/BugReports#167]
CAN'T USE ANY SKILLS ON WARRIOR
## OpenWoW/WoWHead Link

hey guys why i cant use any skills on my warrior? Heroic Strike, Rend, etc. It said "Must have a Melee Weapon equipped in the main hand". Is it bug or something like error? Help me pls

##  Screenshots
![image](https://user-images.githubusercontent.com/65108245/81493802-aa387880-92cd-11ea-8cb0-ce847d60b351.png)

**Comment by Bougah** [comment]
NB = I did equip my Melee Weapon also

**Comment by Fenukshwow** [comment]
Download our custom patch(es).

**Comment by Bougah** [comment]
> Download our custom patch(es).

which one patch(es) ? can u drop the link pls? and how to install it?

**Comment by Bougah** [comment]
> Download our custom patch(es).

because it's happened with my rogue, any skills can be used, it's still said  "Must have a Melee Weapon equipped in the main hand".
