### ISSUE TITLE
Gurzoh

### ISSUE THREAD

**Issue by Shineprelude** [HeroesWoW/BugReports#170]
Attention, please! I don't know if it's right to write here, so I apologize in advance. I have two Gurzoh X axes, they don't work well. When I compare them to T9.5 weapons, there is almost no difference. They are constantly changing and fighting in different ways. Sometimes almost a million are missing. Please fix the problems, there is no logic to pay, free weapons do the same. Thanks! My character's name is Shineprelude

**Comment by Fenukshwow** [comment]
Wrong format
