### ISSUE TITLE
Аttack power Shineprelude

### ISSUE THREAD

**Issue by Shineprelude** [HeroesWoW/BugReports#171]
There has been a problem with my shaman for a long time. when you add attack power, it does not increase but decreases. Two days ago I bought a donor shirt for a promotion and I still have the same problem. When a druid reinforces me with intelligence, my attack decreases again. when i use [Succulent Strider Drumstick] +15000 attack power, it still has the same problem.
![WoWScrnShot_072920_160700](https://user-images.githubusercontent.com/67465814/89044314-72802080-d352-11ea-8941-38c7285651e9.jpg)
![WoWScrnShot_072920_160737](https://user-images.githubusercontent.com/67465814/89044319-757b1100-d352-11ea-8fec-4539c00b4b5b.jpg)
![WoWScrnShot_072920_160757](https://user-images.githubusercontent.com/67465814/89044323-7744d480-d352-11ea-9501-1d06d5b8dea7.jpg)

**Comment by Fenukshwow** [comment]
This is just a visual bug as the WoTLK cannot handle such high numbers as it is never made for it.

**Comment by Shineprelude** [comment]
It's not just a visual error, my DPS is decreasing. I have tried many times.
