### ISSUE TITLE
Kara and Otter spell pen gems are not working currently.

### ISSUE THREAD

**Issue by Dynamite2** [HeroesWoW/BugReports#18]
**## Expected Behavior**
Karazhan bosses can drop a +25 spell pen gem, and Otter can periodically sell a +50 spell pen gem. These items are expected to work similarly to the spell pen offered on tabards/shirts, reducing the resistances of enemies.

**## Current Behavior**
Currently, through testing of Mind blast casts on the wing dummies in the mall, it seems that regardless of the amount of spell pen granted by gems (tested at rating granted from gems: 125 and 225) they do NOT contribute to any more resistance reduction. The exact numbers of my tests can be found at https://heroes-wow.com/index.php?page=bugtracker#

**## Possible Solution**
Reintroduce their function into the realm.

**## Steps to Reproduce**

1. Obtain either the +25 or +50 gems from their respective sources
2. Socket them into two arbitrary items that you can duplicate (IE. a Tier 1 weapon)
3. Compare damage numbers over a redundant number of cast tests (IE. 20-30 mind blasts)
4.

**## Context (Environment)**
Currently, the only way for players to get spell pen for caster toons is either
a) Voter shirt
b) Event tabards
c) Kara and Otter gems

The gap between players who DO and DO NOT have spell pen items grows with gear, considering spell pen is essentially a % increase in spell damage per N rating.

Considering all of the above, constricting the ability to gain up to half of the spell pen cap to 4 two to three week periods a year (Easter, Midsummer, Halloween, and Xmas) is restrictive of players who lack them, and wish to play casters. 

The inclusion of the pen gems on the otter for 1000 shiny, and the pen gems being able to drop from kara bosses, indicates that they are intended to be working, but unfortunately are not.

**## Detailed Description**
Reintroducing the function of the gems would not negatively affect balance. According to others, the spell pen cap is ~850. Players with tabards and shirts with spell pen, along with Spellpiercing enchant and Elixir of Empowerment can expect to have up to 815 spell pen (300+450+35+30). From there, you also have Warlock's Curse Of The Elements which reduces resistances by 130, which already goes over the cap. Reintroducing the function of the gems merely allows players who do not have access to ~2016 Easter tabards to work on their spell pen by either grinding Kara, or looking out for the good snipe of gems from Otter. It will equalize the playing field for casters on Unlimited.

Regards,
Tom

Bug, Mechanic

**Comment by Sappigvleesje** [comment]
They're not bugged, but disabled.

**Comment by Dynamite2** [comment]
Thank you for clarification Sapp, but if that is so, and the intention is to not reintroduce them, why have them on the drop table and sell table for Otter?

**Comment by lordvolom1** [comment]
I'm pretty sure that Terror put them in the game and then realized casters would have a gigantic advantage if they could use them to gem all gear.

**Comment by SirPownzalot** [comment]
It for sure needs to be removed at least from the Otter, otherwise people are wasting upwards of 5k shiny on something that doesn't work as it's implied by being in the shop.

**Comment by Fenukshwow** [comment]
It's removed from the daily vendor
