### ISSUE TITLE
Fix Obliterate main hand damage

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#19]
## OpenWoW/WoWHead Link
Obliterate -> https://wotlk.evowow.com/?spell=51425

## Expected Behavior
Obliterate Main Hand to hit 70-80k

## Current Behavior
Obliterate Main Hand hits for 7-8k

## Possible Solution
Edit the main hand damage and you are done

## Steps to Reproduce

1. Equip 2 hand in main hand
2. Put your dots
3. Use Obliterate
4. Observe

## Context (Environment)
Obliterate is supposed to be stronger than Frost Strike ... previous dev team changed the spell and made it useless and forced DKs to play with 1h 2h, simple because using 2h 2h lowers your damage quite a bit!
Using 1h 2h https://i.imgur.com/nC0ZTn4.png the increase will be from 5k to 50k, which will allow Obliterate to reach Frost Strike and become useful spell in PVP

##  Screenshots
Comparison between Frost Strike and Obliterate -> https://i.imgur.com/fuUwHRi.png

**Comment by Swiftsmoke** [comment]
Issue is now resolved.
