### ISSUE TITLE
Hunter cant equip ammo and most items are shows as ?

### ISSUE THREAD

**Issue by thebenjos** [HeroesWoW/BugReports#20]
## Expected Behavior
I cant equip the levelling ammo for hunters. And none of the ammo is compatable with my T1 weapon either. the items also show as ? instead of a picture of it

## Current Behavior
It doesnt work. i have also re-downloaded the patch 2.0 which i already have an no success.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenukshwow** [comment]
Download the enchant patch 2.1 from the website
https://heroes-wow.com/index.php?page=downloads
