### ISSUE TITLE
 [Threat of Thassarian] using two hand

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#23]
## OpenWoW/WoWHead Link
Threat of Thassarian -> https://wotlk.evowow.com/?spell=66191

## Expected Behavior
Since the talent is working with 2h, it is supposed to make Death Strike, Blood Strike, Plague Strike, Frost Strike and Obliterate to hit twice

## Current Behavior
Watch the video https://youtu.be/7LbMHkpbbTA
It makes only Frost Strike to hit twice

## Steps to Reproduce
1. Equip 2 2h weapons
2. Learn  [Threat of Thassarian]
3. Hit the target
4. Observe

**Comment by Swiftsmoke** [comment]
Issue should be resolved now.
