### ISSUE TITLE
Recent changes, accident bugs to the changed spells

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#24]
Releasing untested or buggy changes isn't quality, the 2 recent "bugfixes" to dks: https://github.com/HeroesWoW/BugReports/issues/21 https://github.com/HeroesWoW/BugReports/issues/23
Ended up being "bigger bugs then before" and made dks unplayable. They have to be fixed ASAP
What do we have here? https://i.imgur.com/JuRJAlf.png a s12 dk, which is complaining about the healers
Please read what i wrote [here ](https://forum.heroes-wow.com/threads/4561-Unlimited-PvP-Class-Changes?p=16116&viewfull=1#post16116) and do the changes, they are more or less necessary. You have to fix https://github.com/HeroesWoW/BugReports/issues/9 and https://github.com/HeroesWoW/BugReports/issues/8 they are going to make our class fun to play and will give good players a way of actually being good by properly rotating their runes

**Comment by Swiftsmoke** [comment]
This is not the place to discuss any issues you have with us making changes, please use the forums for that. This is for reporting bugs.
