### ISSUE TITLE
[PVE][Unlimited] The Burning Furnace Entrance pulling continues

### ISSUE THREAD

**Issue by Madfruity** [HeroesWoW/BugReports#29]
## Expected Behavior

Bosses shouldn't be pull able through wall/stealth
## Current Behavior

LoS (Line of Sight) got fixed few days ago, but i just found new "idea" from other people, how to skip trash mobs. (OR pulling only Bosses, like with Pet pulling before LoS fix)
## Possible Solution

Quite Simple: Add greater/higher Stealth Detection to some certain selected Trash Mobs. Like the Faceless One in Ulduar.
## Steps to Reproduce

1. You need one Rogue/Druid and one Healer Druid/Pala/Shaman/Priest.
2. One Rogue/Druid go in Stealth to the boss and pull it. In the same time the healer(s) start randomly to heal just to get aggro.
3. The following what would happen, is that the Boss run through the wall towards the healer(s).
4. Rest is expected.

## Context (Environment)

I am trying to help to decrease the Number of Bugs in Heroes WoW. 

##  Screenshots
https://gyazo.com/4094b8bfaf0f5513a13b730b7ae7d92f

**Comment by Madfruity** [comment]
Another Possible Solution for this:

Fix the mapping, that NPC's are not running through the wall and second disable/remove Pocket Ritual of Summoning so it goes back unique to warlocks.

**Comment by Fenukshwow** [comment]
Won't do anything regarding this now due to the upcoming core update.
