### ISSUE TITLE
[After Update Bug] [Need to be Fixed] Obliterate proper scaling

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#32]
Obliterate -> https://wotlk.evowow.com/?spell=51425

## Expected Behavior
To deal 100-200k all the time

## Current Behavior
It deals 100-200k only in duels

## Possible Solution
apply the fix to arena and bgs

## Steps to Reproduce

1. use obliterate in arena/bg
2. use obliterate in duel
3. observe
4.

**Comment by Fenukshwow** [comment]
Should be fixed now. I leave this up untill you or someone else can confirm it.

**Comment by nightbaneftw** [comment]
It is fixed, you can close it
