### ISSUE TITLE
Barkskin

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#36]
Barkskin -> https://wotlk.evowow.com/?spell=22812
Imporved Barkskin -> https://wotlk.evowow.com/?spell=63411

The spell reduced damage taken with 50% instead 30%
It is old custom changed, but it needs to be reverted, because it makes druids broken!

**Comment by Fenukshwow** [comment]
As mentioned this has been done on purpose. This will be taken into account with the upcoming class balance which is in the near future.
