### ISSUE TITLE
Nurturing Instinct

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#40]
Nurturing Instinct -> https://wotlk.evowow.com/?spell=33873
The buffed talent works for caster druids aswell, making their heals to be increased with 50% in cat form ... make the custom change to be active only if player has more attack power then spell power

**Comment by Rofleboon** [comment]
https://wotlk.evowow.com/?spell=34300

How is this increasing heals in cat by 50%? Just wondering.

**Comment by lordvolom1** [comment]
I don't think you're talking about the right talent buddy.....

**Comment by lordvolom1** [comment]
It scales from agility, spell power druids don't have agility on their gear etc...... They only get the extra 20%. I'm confused at the point you're trying to make.

**Comment by nightbaneftw** [comment]
Tested in s9t1 caster gear it still increased my heals with 50% ...
I will provide pictures soon!

**Comment by nightbaneftw** [comment]
Looks like you fixed it, which is good!
