### ISSUE TITLE
Flametongue Weapon

### ISSUE THREAD

**Issue by ghost** [HeroesWoW/BugReports#41]
Hello. I am wonderig about Flametongue Weapon enchant for mdps shamans. Was it's damage nerfed due to class balance?

It should have bonus damage from spell power based on weapon speed. Slower weapons will benefit more from spell power. This bonus damage should refer to the additional melee Fire damage per hit, not the increased spell damage, which is a flat amount.

So basically, it could be possible to decrease spell power which it gives, but increase it's damage at least equial to Frostbrand weapon.

Best,
Chastener.

**Comment by nightbaneftw** [comment]
I would prefer shamans running around with 2x flame dealing as much as right now.
Having strong Frostbrand Weapon make them broken it perma slows.
PS Don't you think that suggestions have to be in the forum?

**Comment by ghost** [comment]
Using Frostbrand Weapon on main-hand requires 113k+ haste, which is only available for t7+ donor with haste tab/shirt and trinket. And since too many spells will be fixed and nerfed soon, such as flame shock, that's why I made this suggestion. I am not asking to make "broken" shamans more op, I just wanted them to keep my suggestion in mind after new wave of fixes.
