### ISSUE TITLE
[Post Update Bug] DK Main Hand issues

### ISSUE THREAD

**Issue by nightbaneftw** [HeroesWoW/BugReports#49]
## Expected Behavior
Main hand to deal 100% 

## Current Behavior 
Obliterate main hand deals 15% 
Blood Strike main hand deals 30%
Plague Strike main hand deals 30%
Frost Strike main hand deals  66%

## Context (Environment)
After ToT fix our spells started to deal way lesser damage then before, as you can read from above instead 100% they are doing between 15% and 30%, which hurt us and currently we have 0 chance of killing healers, even if we out gear them in combination with https://github.com/HeroesWoW/BugReports/issues/21

**Comment by Fenukshwow** [comment]
DK damage currently in PvP is fine and won't receive a boost.
