### ISSUE TITLE
Tier 18 Priest heal neck doesnt give crit chance!

### ISSUE THREAD

**Issue by Rpgodx** [HeroesWoW/BugReports#50]
Okay, I will try to be as quick as possible
https://imgur.com/a/zQGnSHh
Okay so in this site there is fully detailed about the bug, With pvp neck, I have 78,26% crit and when I equip my t18 priest neck which should give me 3340 crit (somewhere 10%) instead gives me 0.01%

**Comment by Fenukshwow** [comment]
Delete your cache folder. It showing “T18” says enough
