### ISSUE TITLE
Shaman Tier 2 (8 pieces set bonus)

### ISSUE THREAD

**Issue by Xicsarism** [HeroesWoW/BugReports#51]
Hello, I've found that the scale of shield that Shaman Tier 2 8 piece set bonus gives is not scaled with resilience:

https://imgur.com/a/Hiuq0e1

https://imgur.com/a/CNXsfS9

I hope i was detailed enough

**Comment by Fenukshwow** [comment]
Can you give more info about this? It seems I don't get the same output data as you.
