### ISSUE TITLE
[Unlimited] [Enchant Bug] Enchant Cloak - Speed and Sanctified Cloak of the Scarlet Crusade (T1 Healer Cloak)

### ISSUE THREAD

**Issue by ZappaNappa** [HeroesWoW/BugReports#55]
## Expected Behavior

Haste Rating +15 enchanted onto cloak.

## Current Behavior

That item is not a valid target.

## Possible Solution

Set the Sanctified Cloak to actually be a Cloak category? Not sure if that's the actual bug or if the enchant is not working as it should be.

## Steps to Reproduce

1.Enchant Cloak - Speed and 6 Infinite Dust resource and Runed Adamantite Rod
2.Equip cloak (Sanctified Cloak of the Scarlet Crusade) T1 healer cloak
3.Enchant the cloak, get invalid item error.

## Context (Environment)

Trying to level up my Enchanting to max, also seems to be the best current enchant for my cloak. Maybe not. I haven't gotten to max yet maybe there's a better one later.

##  Screenshots

Item preview
https://i.imgur.com/Wux2cBP.jpg
After attempting to enchant
https://i.imgur.com/lkHlAik.jpg

**Comment by Fenukshwow** [comment]
This is fixed with the latest enchant patch.
