### ISSUE TITLE
Mind flay not channeling through.

### ISSUE THREAD

**Issue by Rofleboon** [HeroesWoW/BugReports#56]
http://wotlk.cavernoftime.com/spell=48156

## Expected Behavior

It should be channeling for its full duration.

## Current Behavior

It stops channeling 1 Tick before ending.

## Steps to Reproduce

1.Enter a Duel / Arena / Battleground (I've only noticed it in PvP since I only PvP.)
2.Cast Mind Flay
3.Notice the spell not channeling to the end. 
4.When using an Addon called Quartz where you can see supposed tick timers you can see that 1 tick is missing.

**Comment by Fenukshwow** [comment]
It's handled via the haste entry we put on it due to the high amount of haste. If we disable it mindflay will tick too many times. In the feature we might take a look at this once again but for now not a prior.
