### ISSUE TITLE
Hunter Sniper Training

### ISSUE THREAD

**Issue by Gw3nn4** [HeroesWoW/BugReports#60]
The ability of hunter class in survival tree Sniper Training isnt working.
#

## Expected Behavior
increases the critical strike chance of kill shot ability by 5, 10, 15 % , and while standing still for 6 sec, you gain Sniper Training increasing the damage done by your Steady Shot, Aimed Shot, Black Arrow and Explosive 
Shot by 2, 4 , 6 % for 15 sec.

## Current Behavior
nothing buff doesnt work, can stan for hours and dont get the buff

## Possible Solution
maybe ability is deactivated 
## Steps to Reproduce
1.Get a hunter
2. skill survival tree till 3/3 sniper training
3.stand still for 6 sec
4.

## Context (Environment)
raid, infight and out of fight
mall infight and out of fight
world infight and out of fight

having this ability would just increase the damage of a hunter slightly

**Comment by Fenukshwow** [comment]
This is disabled on purpose
changelogs #rev665
