### ISSUE TITLE
Donor bow(s) problems. (Stats etc)

### ISSUE THREAD

**Issue by lordvolom1** [HeroesWoW/BugReports#62]
1. The BoA bow and the BoP bow give the same attack power and haste at ALL levels. BoP should give more stats than BoA.

2. The haste and attack power on them doesn't start increasing until you get them to level 7. So you get no upgrades on haste/attack power from 1-6.

3. The level 1 BoP bow gives mana for some reason.

This should be fixed, as it's been wrong ever since they've been out lol. Please respond once you see this and if it will be fixed. Thank you.

(I didn't bother posting screenshots as this is something that can very easily be seen in-game.)

**Comment by Fenukshwow** [comment]
Fixed

**Comment by lordvolom1** [comment]
The haste isn't fixed, the attack power is tho

**Comment by Fenukshwow** [comment]
Haste scaling added, more info in changelogs.
