### ISSUE TITLE
Fix T1 Weapons

### ISSUE THREAD

**Issue by Mortymerchan** [HeroesWoW/BugReports#63]
## Expected Behavior
Fix DMG from T1 Weapons:
• Waraxe of the Scarlet Crusade
• Cudgel of the Scarlet Crusade
• Longblade of the Scarlet Crusade
• Shanker of the Scarlet Crusade

## Possible Solution
Make DMG to correct for dat tier

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description
To big DMG from dat weapon.

**Comment by Fenukshwow** [comment]
Please describe what "To big DMG" means according to you.

**Comment by Mortymerchan** [comment]
> Please describe what "To big DMG" means according to you.

Same issue → https://github.com/HeroesWoW/BugReports/issues/66

**Comment by Fenukshwow** [comment]
Thank you, I will look into it.

**Comment by fpalfapvp** [comment]
Make something

Fix DMG from T1 Weapons:
• Waraxe of the Scarlet Crusade
• Cudgel of the Scarlet Crusade
• Longblade of the Scarlet Crusade
• Shanker of the Scarlet Crusade

![d31](https://user-images.githubusercontent.com/35656427/50223806-d7b51700-03a4-11e9-91d1-68a83892da31.png)

**Comment by Fenukshwow** [comment]
Fixed
