### ISSUE TITLE
Buff Warlock DPS (Make it more popular)

### ISSUE THREAD

**Issue by Mortymerchan** [HeroesWoW/BugReports#65]
## Expected Behavior
Even for T5.5 bosses full t5.5 warlock give lowest dps than t4 druid.

## Current Behavior
Too little damage from abilities in this equipment

## Possible Solution
Increase DMG from dots and main abilities:
• Curse of Agony +20% DMG
• Corruption +40% DMG
• Incinerate +20% DMG
• Shadow Bolt +20% DMG
• Soul FIre +20% DMG
• Immolate +20% DMG
• Seed of Corruption +25% DMG

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
Warlock is one of the most unpopular classes on this server. I want to change this. The priest simply uses two curses and already 1+ million DPS, the same druid or mage.

## Detailed Description
Even using a sufficiently serious rotation, it is impossible to achieve the desired results.

## Possible Implementation
Increase DPS from the main attacking abilities.

##  Screenshots
 https://imgur.com/a/RewXDVl

**Comment by Fenukshwow** [comment]
Use our forum for class suggestions
