### ISSUE TITLE
Wep stats bug

### ISSUE THREAD

**Issue by denis1892** [HeroesWoW/BugReports#66]
## Expected Behavior
T5.5 one-handed weapons provide lesscritical chance rate than T1 1handers

## Current Behavior
T1 one-handed weapons provide more critical chance rate than T5.5 1handers

## Possible Solution
Re-work the critical strike rating of the weapons.

## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description
I am not sure maybe this problem exists with other tier weps, havent paid attention to that.

##  Screenshots
[https://imgur.com/a/Pf1InEv](url)

**Comment by denis1892** [comment]
SS:
![wowscrnshot_092218_200130](https://user-images.githubusercontent.com/43502208/45920352-27b63780-bea3-11e8-8da1-98c74122ba98.jpg)
![wowscrnshot_092218_200133](https://user-images.githubusercontent.com/43502208/45920355-2c7aeb80-bea3-11e8-8a46-fc4922d4f0dd.jpg)

**Comment by Mortymerchan** [comment]
> SS:
> ![wowscrnshot_092218_200130](https://user-images.githubusercontent.com/43502208/45920352-27b63780-bea3-11e8-8da1-98c74122ba98.jpg)
> ![wowscrnshot_092218_200133](https://user-images.githubusercontent.com/43502208/45920355-2c7aeb80-bea3-11e8-8a46-fc4922d4f0dd.jpg)

![wowscrnshot_092318_103227](https://user-images.githubusercontent.com/43497316/45925365-57555600-bf1c-11e8-8c13-e2662a94afa9.jpg)
![wowscrnshot_092318_103234](https://user-images.githubusercontent.com/43497316/45925366-57555600-bf1c-11e8-9bc9-9534694a93fd.jpg)

**Comment by fpalfapvp** [comment]
When its will be fixed?

**Comment by Fenukshwow** [comment]
Fixed
