### ISSUE TITLE
[Unlimited] Enhancement shaman T1 & T2  stamina overbuff.

### ISSUE THREAD

**Issue by Mortymerchan** [HeroesWoW/BugReports#67]
## Expected Behavior
T1 & T2 Enhancement shaman sets have overbuffed stamina.

## Possible Solution
Make correct stats.

## Steps to Reproduce

1.
2.
3.
4.

##  Screenshots
https://imgur.com/a/VisWnTZ

**Comment by Fenukshwow** [comment]
Fixed
