### ISSUE TITLE
[Unlimited] Enhancement shaman fix to correct haste raiting.

### ISSUE THREAD

**Issue by Mortymerchan** [HeroesWoW/BugReports#68]
## Current Behavior
Different items have different haste ratings. T1 have haste raiting, t2 have melee haste raiting, t3 again has haste raiting.

## Possible Solution
Make one haste raiting for all items

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenukshwow** [comment]
Fixed with #67
