### ISSUE TITLE
[Unlimited] Priest Wrists 3 Socket on all item sets.

### ISSUE THREAD

**Issue by Mortymerchan** [HeroesWoW/BugReports#69]
## Expected Behavior
2 sockets in wrists.

## Current Behavior
3 Sockets in all wrists.

## Possible Solution
Change 3 socket to shoulders 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenukshwow** [comment]
It is not possible to remove the 3rd socket as people might have donation gems in the socket. (Unfortunately) it stays this way.
