### ISSUE TITLE
[Unlimited] Druid shapeshift attack power problems on several items.

### ISSUE THREAD

**Issue by Mortymerchan** [HeroesWoW/BugReports#70]
## Expected Behavior
All 2hand algility weapon must have the same amount.

## Current Behavior
Starting with T1 weapons, staffs/maces/swords/polearms have different amount attack power.

## Possible Solution
Make same number for all 2hand algility weapon.
• T1 → 197212
• T2 → 207111
• T3 → 217505
• T4 → 228419
• T5 → 232659
• T5.5 → 239878
And others ...

## Steps to Reproduce

1.
2.
3.
4.

##  Screenshots
![4123](https://user-images.githubusercontent.com/43497316/45943105-b2a34900-bfed-11e8-95a2-252ce4b8f837.png)->

**Comment by Fenukshwow** [comment]
The shapeshift attackpower is different due to the weapon speed.
