### ISSUE TITLE
[Unlimited] 2Hand Tank weapon dmg different on several items.

### ISSUE THREAD

**Issue by Mortymerchan** [HeroesWoW/BugReports#71]
## Expected Behavior
All tanking 2hand weapons have same damage as it answers proper tier

## Current Behavior
• Broadsword of the Demon Blood (T5 Sword) Lowest dmg then T5 mace;
• Broadsword of the Torturer (T5.5 Sword) Lowest dmg then T5.5 mace;

## Possible Solution
Make same stats like have maces

## Steps to Reproduce

1.
2.
3.
4.

**Comment by fpalfapvp** [comment]
Somebody doing dat?

**Comment by Fenukshwow** [comment]
Fixed
