### ISSUE TITLE
[Unlimited] Warlock - weird dmg from pets spells

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#77]
## OpenWoW/WoWHead Link
• Sucubus - Lash of Pain 
• Imp - Firebolt

## Expected Behavior
More or less the same damage, without large drops and jumps.

## Current Behavior
• Sucubus - Lash of Pain - extremely low dmg. 36-40k hit on full t5.5 gear with Voter and Donor Buff.
~ 
• Imp - Fire Bolt - dmg start from 125 k to 385 k normal dmg withou critical strikes. I think this interval to big.

## Possible Solution
• Sucubus - Lash of Pain - make correct dmg answer the equipment on char.
~ 
• Imp - Fire Bolt - make not so big intervals in dmg.

## Detailed Description

Imp dmg on heroes wow (Youtube) - https://youtu.be/G_gLTR43uEA.
Imp dmg  on my test server → https://youtu.be/GZ-6u_0Fn5k

##  Screenshots
![wowscrnshot_092418_164310](https://user-images.githubusercontent.com/43497316/45955769-7685dd80-c019-11e8-8b1f-2d03090152cd.jpg)

**Comment by Fenukshwow** [comment]
Some spells are buffed/nerfed - scaled towards the 255 content. What's exactly the bug right here according to you?

**Comment by fpalfapvp** [comment]
> Some spells are buffed/nerfed - scaled towards the 255 content. What's exactly the bug right here according to you?

 Sucubus - Lash of Pain hit only 36 k? Very small damage for 255 content + gear.

And imp firebolt starting from 120 k and stops on 380k without critical dmg. Its dmg walks ~ 220 k i think that interval to much.

**Comment by fpalfapvp** [comment]
> Some spells are buffed/nerfed - scaled towards the 255 content. What's exactly the bug right here according to you?

**UPDT:** Dat problems with dmg only on custom server mobs like dat Dummy. On Orgrimmar dummys all fine and haven't dat weird interval.

**Comment by Fenukshwow** [comment]
This will be looking into when the class balance hits in the near future.
