### ISSUE TITLE
Donor rogue rings are worse than the PvE equivalent (Back Neck and Ring Socket issue)

### ISSUE THREAD

**Issue by Prazirogue** [HeroesWoW/BugReports#79]
I have a Devilish donor ring, which i used a T5.5 Jewl token to upgrade and it seems the T5.5 none donor jewl has more stats. 400 more agility and 92 more attack power. Also the donor back neck and rings have 0 sockets while the other pve version have 2 sockets.

**Comment by Fenukshwow** [comment]
Fixed
