### ISSUE TITLE
[Unlimited] Warlock - Molten Core talent work in PvP and not working in PvE

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#83]
## OpenWoW/WoWHead Link
https://wotlk.evowow.com/?spell=47247

## Expected Behavior
12% chance to gain the Molten Core effect when your Corruption deals damage. The Molten Core effect empowers your next 3 Incinerate or Soul Fire spells cast within 15 sec.

Incinerate - Increases damage done by 18% and reduces cast time by 30%.

Soul Fire - Increases damage done by 18% and increases critical strike chance by 15%

## Current Behavior
Talent prock in PvP but not proking in PvE in instances and raids. How it is?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenukshwow** [comment]
Same as #73

**Comment by fpalfapvp** [comment]
> Same as #73

Not same. in #73 it is said that talent does not work at all. But in fact it does not work only in PvE and pretty good work in PvP.

**Comment by Fenukshwow** [comment]
The spell itself, in general, is bugged hence I linked it together. The whole spell needs an overhaul.
