### ISSUE TITLE
[Unlimited] Buff Rogue items stats by 2-2.5%

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#85]
## Possible Solution
Buff Rogue items stats by 2-2.5% . I think its make rogue more popular. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenukshwow** [comment]
You mean there's an issue between the tier scaling or you want to see an improvement on rogue stats by an X% of stat increase?

**Comment by fpalfapvp** [comment]
> You mean there's an issue between the tier scaling or you want to see an improvement on rogue stats by an X% of stat increase?

Think need increase stat scale by 2%-2.5%. Other class have more stat scale between tiers.

**Comment by Fenukshwow** [comment]
This is not a bug, but a suggestion.
