### ISSUE TITLE
[Unlimited] Reduce the amount of silver coin for upgrade Vote Bags

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#86]
## Current Behavior
Reduce the amount of silver coin for upgrade Vote Bags

## Possible Solution
The price for buying one bag, and then further improving is too big. At the same time, the price does not justify the quality. For example, take Voter's Backpack I and Voter's Backpack II - we get a good boost of characteristics which is equal to the price spent in silver coins, but then only the price increase and the minimum benefit from the improvement. 

What in my opinion you need to do:
Reduce the price of upgrade by several times in all currencies.
**OR** Add more stats between levels of upgrade. Add more resistance by level / add some spell penetration / add hit and crit rating.

**Same thing to do with Donors Bags!**

## Steps to Reproduce

1.
2.
3.
4.

##  Screenshots

![bezymiannyi_800](https://user-images.githubusercontent.com/35656427/47151397-4eb92b00-d2e2-11e8-9507-a0b98d058165.jpg)

**Comment by Fenukshwow** [comment]
This is not a bug.
