### ISSUE TITLE
I purchased a duel wield scroll and a titans grip scroll the other night, I accidentally used the titans grip scroll first, giving me duel wield. Now I am stuck with a duel wield spec, and a scroll. It did not provide titans grip.

### ISSUE THREAD

**Issue by Monoxidereborn** [HeroesWoW/BugReports#89]
## Expected Behavior

Honestly, I know for a fact that I had purchased both scrolls correctly. I had 17 gold coins left before purchase and now have only 2. I used the titans grip scroll on accident first and it gave me duel wield. Could I please just get them swapped out? I will even pay 1 gold difference..
## Current Behavior

I figured that it was a bug, and would be understandable that a mistake was made but it still gave me the wrong skill.
## Possible Solution

Make sure you cannot use titans grip before duel wield.
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)
I can no longer use my titans grip, in which I needed to continue gearing and further progress on my druid. Also, I donated real money for in-game currency that sadly went to waste..

**Comment by fpalfapvp** [comment]
Its not a bug. Server have "no refund polici" - nobody help you. Sorry.

**Comment by Fenukshwow** [comment]
Daygu is right with this.
