### ISSUE TITLE
[Unlimited] Halloween Weapon Not usable

### ISSUE THREAD

**Issue by fpalfapvp** [HeroesWoW/BugReports#92]
## Current Behavior
Halloween Weapon Not usable

## Possible Solution
Update Patch!

## Steps to Reproduce
ill have update new enchant patch but dat not help

##  Screenshots
![asd4](https://user-images.githubusercontent.com/35656427/47614653-e02b5880-daab-11e8-980c-9c7b62b8994e.png)

**Comment by Fenukshwow** [comment]
Download the latest enchant patch and you can use it. We had an issue with the patch which has been resolved 2 days ago.
