### ISSUE TITLE
Gold coins

### ISSUE THREAD

**Issue by hiimnd** [HeroesWoW/BugReports#93]
I am not recieving any gold coins. The problem started after midsummer festival event after I bought titan grip.
Username: adik2
Email: adiceq@gmail.com
Registration date: 2018-07-22 12:18:25

I got cca. 11days played on my account. Recieved 9gc so far. Last gc recieved was 100+ hours ago.

**Comment by Fenukshwow** [comment]
You need to play the game (PvP / PvE) just being online for an X amount of hours doesn't give gold coins at all. The system is working fine as I received a couple this month myself.

**Comment by hiimnd** [comment]
Ikr, I wouldnt be posting if I haven't tested it I went from t5,5 to t7 on dudu and from t1 to t5,5 on my lock...  My friends that are playing with me are recieving gc just fine and thats why I am reporting it
