### ISSUE TITLE
ihavebanned

### ISSUE THREAD

**Issue by qochora1** [HeroesWoW/BugReports#94]
i have banned 2 years ago and i create now new account and cant join 
![wowscrnshot_103018_132931](https://user-images.githubusercontent.com/44604644/47710872-4d2a2400-dc4d-11e8-842e-9503eecb553d.jpg)  need hellp

**Comment by fpalfapvp** [comment]
Maybe you have banned ip adress. Btw need write to server stuff / not in bugtracker
