### ISSUE TITLE
bought shoes for the currency, opened, and there on the other very class

### ISSUE THREAD

**Issue by Bratyxa007** [HeroesWoW/BugReports#98]
## Detailed Description

**bought shoes for the currency, opened, and there on the other very class**
##  Screenshots

https://gyazo.com/7880933532f2ca01da6a6c9fe6f0ee7c

**Comment by Fenukshwow** [comment]
Fixed, send me a message on discord (fenuks) or send me an in game mail (fenuks) so I can swap the item for you. Sorry for the inconvenience.
